### ISSUE TITLE
[Bug] Crafting Inventory

### ISSUE THREAD

**Issue by Tarnadas** [Monospark/ActionControl#3] opened 2016-10-05 16:24 UTC
edit:
I just read this (https://forums.spongepowered.org/t/tools-actioncontrol-v1-1-control-crafting-mining-combat-and-more/10372/76) post, so I assume this will be fixed as soon as the Sponge team updates their inventory API

Assume you set any rule that disables crafting of a specific item. Now if you put this item in a crafting menu, you can place it there, but you won't be able to put it back in your inventory.

Example:

```
player-filter = "!{'permissions': {'item.craft': true}}",
action-rules {

    craft {
        filter {
            result = "{'type': 'minecraft.planks'}"
        },
        response {
            match = [
                "deny"
            ]
        }
    }
}
```

There is also some weird behaviour, when I use regex.

```
player-filter = "!{'permissions': {'item.craft': true}}",
action-rules {

    craft {
        filter {
            result = "{'type': r'minecraft.*'}"
        },
        response {
            match = [
                "deny"
            ]
        }
    }
}
```

This example has exactly the same behaviour as the upper one, but applies to all minecraft vanilla items.

```
player-filter = "!{'permissions': {'item.craft': true}}",
action-rules {

    craft {
        filter {
            result = "{'type': r'.*'}"
        },
        response {
            match = [
                "deny"
            ]
        }
    }
}
```

This example should deny every crafting recipe, including mods. It has a different behaviour, because now you cannot even put items in a crafting menu. Also if you try to put them back in your inventory after trying to put them in a crafting menu, the first time it won't work, but every subsequent try will work

**Comment by Milchshakee** [comment] 2016-10-05 20:58
I will look into this.

**Comment by Milchshakee** [comment] 2016-10-08 10:07
Yeah all of these issues are caused by using the incomplete inventory api and should be fixed in the next ActionControl update, which will support 1.10 and API 5.

**Closed as completed by Milchshakee** 2016-10-08 10:07 UTC
